# Generated by Django 6.0.7 on 2026-07-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patente", models.CharField(max_length=200)),
                ("modelo", models.TextField(blank=True)),
                ("done", models.BooleanField(default=False)),
                ("Registro_Creado", models.DateTimeField(auto_now_add=True)),
                ("Registro_Actualizado", models.DateTimeField(auto_now=True)),
                ("info_adicional", models.TextField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="productos"),
                ),
            ],
        ),
    ]
