# Generated by Django 6.0.7 on 2026-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_remove_task_campo1_remove_task_campo2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="patente",
            field=models.CharField(max_length=200),
        ),
    ]
