# Generated by Django 6.0.7 on 2026-07-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_alter_task_patente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="done",
        ),
        migrations.AddField(
            model_name="task",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Incautado", "Incautado"),
                    ("En Proceso", "En Proceso"),
                    ("Liberado", "Liberado"),
                ],
                default="Incautado",
                max_length=20,
            ),
        ),
    ]
